/* include the declarations from the original 'single-headers */
#include "orig/beeper.h"
#include "orig/clk.h"
#include "orig/crt.h"
#include "orig/mem.h"
#include "orig/kbd.h"

#include "orig/ay38910.h"
#include "orig/i8255.h"
#include "orig/m6502.h"
#include "orig/m6522.h"
#include "orig/m6526.h"
#include "orig/m6569.h"
#include "orig/m6581.h"
#include "orig/mc6845.h"
#include "orig/mc6847.h"
#include "orig/z80.h"
#include "orig/z80ctc.h"
#include "orig/z80pio.h"

#include "orig/atom.h"
#include "orig/c64.h"
#include "orig/cpc.h"
#include "orig/kc85.h"
#include "orig/z1013.h"
#include "orig/z9001.h"
#include "orig/zx.h"

#include "orig/sokol_app.h"
#include "orig/sokol_args.h"
#include "orig/sokol_audio.h"
#include "orig/sokol_gfx.h"
#include "orig/sokol_time.h"
