/* include the declarations from the decl-only headers */
#include "decl/beeper.h"
#include "decl/clk.h"
#include "decl/crt.h"
#include "decl/mem.h"
#include "decl/kbd.h"

#include "decl/ay38910.h"
#include "decl/i8255.h"
#include "decl/m6502.h"
#include "decl/m6522.h"
#include "decl/m6526.h"
#include "decl/m6569.h"
#include "decl/m6581.h"
#include "decl/mc6845.h"
#include "decl/mc6847.h"
#include "decl/z80.h"
#include "decl/z80ctc.h"
#include "decl/z80pio.h"

#include "decl/atom.h"
#include "decl/c64.h"
#include "decl/cpc.h"
#include "decl/kc85.h"
#include "decl/z1013.h"
#include "decl/z9001.h"
#include "decl/zx.h"

#include "decl/sokol_app.h"
#include "decl/sokol_args.h"
#include "decl/sokol_audio.h"
#include "decl/sokol_gfx.h"
#include "decl/sokol_time.h"